test:
  image: alpine
  services:
    - name: registry.red-soft.biz:5000/docker-images/red-database/enterprise:3
      alias: RedDatabase
    - name: docker:dind
  before_script:
    - sleep 10h
    - bundle exec rake db:build
  script: bundle exec rake test