test:
  variables:
    DOCKER_DRIVER: overlay2
    DEBIAN_FRONTEND: noninteractive
    TZ: "Europe/Moscow"
  image: ruby:2.7-slim
#  services:
#    - name: registry.red-soft.biz:5000/docker-images/red-database/enterprise:3
#      alias: RedDatabase
  before_script:
#    - sleep 10h
    - ls -l /usr/lib
    - apt-get update
    - apt-get install curl libncurses5 git -y
    - curl http://builds.red-soft.biz/release_hub/rdb30/3.0.8.0/download/red-database:linux-x86_64-enterprise:3.0.8.0:bin -o /tmp/installer
    - chmod +x /tmp/installer &&\
    - /tmp/installer --architecture Super --mode unattended
    - cp -R /opt/RedDatabase/include/* /usr/include
    - cp -R /opt/RedDatabase/lib/* /usr/lib/x86_64-linux-gnu
    - bundle install
    - bundle exec rake db:build
  script: bundle exec rake test